name: Django                                  # workflow name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build application
        run: echo "Building the application..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Running tests..."

  integration:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Allow this job to fail without affecting the workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run integration tests
        run: |
          echo "Running integration tests..."
          exit 1  # Simulate a failed integration test

  deploy:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy application
        run: echo "Deploying the application..."

  artifact:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact file
        run: echo "hello" > hello.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: hello.txt
